# Generated by Django 5.1.6 on 2025-02-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('motor', models.CharField(max_length=50)),
                ('velocidad', models.CharField(max_length=50)),
                ('manual', models.CharField(max_length=50)),
                ('pasajeros', models.CharField(max_length=50)),
            ],
        ),
    ]
